<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * HeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderRepository extends EntityRepository
{

    public function getAllPublishedItems()

    {
        return $this->createQueryBuilder('h')
            ->select('h')
            ->where('h.published = :published')
            ->setParameter('published',1)
            ->orderBy('h.date', 'DESC')
            ->getQuery()
            ->getResult();
    }



    public function findByAuthor($author)
    {
        $qb = $this->createQueryBuilder('h');

        $qb->where('h.user_id = :author')

            ->setParameter('author', $author);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function quantityCvSpace($author)
    {
        return $this->createQueryBuilder('h')
            ->select('COUNT(h)')
            ->where('h.user_id = :author')
            ->setParameter('author', $author)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function quantityOfPublishedItems()
    {
        return $this->createQueryBuilder('h')
            ->select('COUNT(h)')
            ->where('h.published = :published')
            ->setParameter('published',1)
            ->getQuery()
            ->getSingleScalarResult();
    }




}
